[workspace]
members = [
    "rust-test-crate",
    "rust-test-crate-add",
    "rust-test-crate-divide",
    "rust-test-crate-multiply"
]
resolver = "2"

[workspace.package]
license = "MIT"
edition = "2021"
rust-version = "1.79.0"

[workspace.dependencies]
